const researchRanking = [
  {
    name: "Indian Institute of Science",
    city: "Bengaluru",
    rank: 1,
    state: "Karnataka",
  },
  {
    name: "Indian Institute of Technology Madras",
    city: "Chennai",
    rank: 2,
    state: "Tamil Nadu",
  },
  {
    name: "Indian Institute of Technology, Delhi",
    city: "New Delhi",
    rank: 3,
    state: "Delhi",
  },
  {
    name: "Indian Institute of Technology, Bombay",
    city: "Mumbai",
    rank: 4,
    state: "Maharashtra",
  },
  {
    name: "Indian Institute of Technology, Kharagpur",
    city: "Kharagpur",
    rank: 5,
    state: "West Bengal",
  },
  {
    name: "Indian Institute of Technology Kanpur",
    city: "Kanpur",
    rank: 6,
    state: "Uttar Pradesh",
  },
  {
    name: "Tata Institute of Fundamental Research",
    city: "Mumbai",
    rank: 7,
    state: "Maharashtra",
  },
  {
    name: "Indian Institute of Technology, Roorkee",
    city: "Roorkee",
    rank: 8,
    state: "Uttarakhand",
  },
  {
    name: "All India Institute of Medical Sciences, Delhi",
    city: "New Delhi",
    rank: 9,
    state: "Delhi",
  },
  {
    name: "Vellore Institute of Technology",
    city: "Vellore",
    rank: 10,
    state: "Tamil Nadu",
  },
  {
    name: "Homi Bhabha National Institute",
    city: "Mumbai",
    rank: 11,
    state: "Maharashtra",
  },
  {
    name: "Indian Institute of Technology Hyderabad",
    city: "Hyderabad",
    rank: 12,
    state: "Telangana",
  },
  {
    name: "Jadavpur University",
    city: "Kolkata",
    rank: 13,
    state: "West Bengal",
  },
  {
    name: "Jawaharlal Nehru University",
    city: "New Delhi",
    rank: 14,
    state: "Delhi",
  },
  {
    name: "Banaras Hindu University",
    city: "Varanasi",
    rank: 15,
    state: "Uttar Pradesh",
  },
  {
    name: "University of Delhi",
    city: "Delhi",
    rank: 16,
    state: "Delhi",
  },
  {
    name: "Indian Institute of Science Education & Research, Pune",
    city: "Pune",
    rank: 17,
    state: "Maharashtra",
  },
  {
    name: "Academy of Scientific & Innovative Research",
    city: "Ghaziabad",
    rank: 18,
    state: "Uttar Pradesh",
  },
  {
    name: "Jamia Millia Islamia, New Delhi",
    city: "New Delhi",
    rank: 19,
    state: "Delhi",
  },
  {
    name: "Indian Institute of Technology (Indian School of Mines)",
    city: "Dhanbad",
    rank: 20,
    state: "Jharkhand",
  },
  {
    name: "Anna University",
    city: "Chennai",
    rank: 21,
    state: "Tamil Nadu",
  },
  {
    name: "Bharathiar University",
    city: "Coimbatore",
    rank: 22,
    state: "Tamil Nadu",
  },
  {
    name: "National Institute of Technology, Tiruchirappalli",
    city: "Tiruchirappalli",
    rank: 23,
    state: "Tamil Nadu",
  },
  {
    name: "National Institute of Technology Rourkela",
    city: "Rourkela",
    rank: 24,
    state: "Odisha",
  },
  {
    name: "Institute of Chemical Technology",
    city: "Mumbai",
    rank: 25,
    state: "Maharashtra",
  },
  {
    name: "Indian Institute of Technology Indore",
    city: "Indore",
    rank: 26,
    state: "Madhya Pradesh",
  },
  {
    name: "University of Hyderabad",
    city: "Hyderabad",
    rank: 27,
    state: "Telangana",
  },
  {
    name: "Aligarh Muslim University",
    city: "Aligarh",
    rank: 28,
    state: "Uttar Pradesh",
  },
  {
    name: "Panjab University",
    city: "Chandigarh",
    rank: 29,
    state: "Chandigarh",
  },
  {
    name: "Manipal Academy of Higher Education, Manipal",
    city: "Manipal",
    rank: 30,
    state: "Karnataka",
  },
  {
    name: "Amrita Vishwa Vidyapeetham",
    city: "Coimbatore",
    rank: 31,
    state: "Tamil Nadu",
  },
  {
    name: "Indian Institute of Science Education & Research, Kolkata",
    city: "Mohanpur",
    rank: 32,
    state: "West Bengal",
  },
  {
    name: "Birla Institute of Technology & Science - Pilani",
    city: "Pilani",
    rank: 33,
    state: "Rajasthan",
  },
  {
    name: "Indian Institute of Technology, Gandhinagar",
    city: "Gandhinagar",
    rank: 34,
    state: "Gujarat",
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    city: "Patiala",
    rank: 35,
    state: "Punjab",
  },
  {
    name: "S.R.M. Institute of Science and Technology",
    city: "Chennai",
    rank: 36,
    state: "Tamil Nadu",
  },
  {
    name: "Indian Institute of Technology Bhubaneswar",
    city: "Bhubaneswar",
    rank: 37,
    state: "Odisha",
  },
  {
    name: "Amity University",
    city: "Gautam Budh Nagar",
    rank: 38,
    state: "Uttar Pradesh",
  },
  {
    name: "Indian Institute of Technology, Mandi",
    city: "Mandi",
    rank: 39,
    state: "Himachal Pradesh",
  },
  {
    name: "Indian Institute of Engineering Science and Technology, Shibpur",
    city: "Howrah",
    rank: 40,
    state: "West Bengal",
  },
  {
    name: "Indian Institute of Technology, Patna",
    city: "Patna",
    rank: 41,
    state: "Bihar",
  },
  {
    name: "National Institute of Mental Health & Neuro Sciences, Bangalore",
    city: "Bangalore",
    rank: 42,
    state: "Karnataka",
  },
  {
    name: "Alagappa University",
    city: "Karaikudi",
    rank: 43,
    state: "Tamil Nadu",
  },
  {
    name: "Shanmugha Arts Science Technology & Research Academy",
    city: "Thanjavur",
    rank: 44,
    state: "Tamil Nadu",
  },
  {
    name: "Siksha `O` Anusandhan",
    city: "Bhubaneswar",
    rank: 45,
    state: "Odisha",
  },
  {
    name: "Malaviya National Institute of Technology",
    city: "Jaipur",
    rank: 46,
    state: "Rajasthan",
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    city: "Bhubaneswar",
    rank: 47,
    state: "Odisha",
  },
  {
    name: "Saveetha Institute of Medical and Technical Sciences",
    city: "Chennai",
    rank: 48,
    state: "Tamil Nadu",
  },
  {
    name: "Indian Institute of Science Education & Research Bhopal",
    city: "Bhopal",
    rank: 49,
    state: "Madhya Pradesh",
  },
  {
    name: "National Institute of Technology, Silchar",
    city: "Silchar",
    rank: 50,
    state: "Assam",
  },
];
export default researchRanking;
